(in-package :jvm-opcodes)

(define-record class-file ()
  (magic         :type u4 :initform #xcafebabe)
  (minor-version :type u2 :initform 0)
  (major-version :type u2 :initform 52)
  (constant-pool :type (pool constant-info) :initarg :constant-pool)
  (access-flags :type access-flags :initarg :access-flags)
  (this-class   :type constant :initarg :this-class)
  (super-class  :type constant :initarg :super-class)
  (interfaces   :type (pool interface) :initarg :interfaces)
  (fields       :type (pool field) :initarg :fields)
  (methods      :type (pool method) :initarg :methods)
  (attributes   :type (pool attributes) :initarg :attributes))
   
(define-record pool (element-type)
  ((count :type u2)
   (records :type (sequence element-type) :initarg :records)))
(defmethod initialize-instance :after ((pool pool))
  (setf (count pool) (length records)))

(define-enum (access-flags 2)
  (:public     #x0001)
  (:private    #x0002)
  (:protected  #x0004)
  (:static     #x0008)
  (:final      #x0010)
  (:super      #x0020)
  (:volatile   #x0040)
  (:transient  #x0080)
  (:interface  #x0200)
  (:abstract   #x0400)
  (:synthetic  #x1000)
  (:annotation #x2000)
  (:enum       #x4000)
  (:module     #x8000))
